### ISSUE TITLE
内容补充

### ISSUE THREAD

**Issue by S-Canister** [IRobot-Algorithm/GUIDE#21]
1、数学基础：我觉得应该加入相关数学基础的补充，例如从最基本的微积分、矩阵、随机过程、概率论到基本的最优化方法等
2、深度学习里面要补充一些经典的机器学习算法吗？
3、机械臂和模拟器的方向也让人加上吧

**Comment by Gy920** [comment]
机械臂方向我觉得可以加（比如命名为robotic方向)，但仿真器不应该是一个大的方向，我们应该把他归结到robotic方向中的一个模块中，理由是:
- 我们不是做图形学上的引擎开发，其实我们所谓做的仿真器，其实是拿别人的引擎，然后放自己的场景和机器人进去，所以这个不应该是一个大方向，只是我们做机器人中的一个模块（这类仿真器比如像 [isaac sim](https://developer.nvidia.com/isaac/sim)，gazebo ,[airsim](https://github.com/microsoft/AirSim) 等等）

**Comment by Gy920** [comment]
数学基础应该要添加，你说的感觉就很好

**Comment by Gy920** [comment]
- 深度学习部分确实应该加一些机器学习的东西： kmeans，PCA，岭回归，KNN这些，但不要加太多
- 其次现在写的太详细了，一些能缩减的缩减一下
- 进阶里面加可以加一些新东西，比如像 [clip](https://github.com/openai/CLIP/tree/main), [sam](https://sam2.metademolab.com/), [grounding dino](https://github.com/IDEA-Research/GroundingDINO), [DINO v2](https://github.com/facebookresearch/dinov2/tree/main)，这些可能会帮助我们日常开发的**Foundation models** , 比如这里使用sam去辅助我们标数据集（分割类）等等

**Comment by Gy920** [comment]
> 机械臂方向我觉得可以加（比如命名为robotic方向)，但仿真器不应该是一个大的方向，我们应该把他归结到robotic方向中的一个模块中，理由是:
> 
> * 我们不是做图形学上的引擎开发，其实我们所谓做的仿真器，其实是拿别人的引擎，然后放自己的场景和机器人进去，所以这个不应该是一个大方向，只是我们做机器人中的一个模块（这类仿真器比如像 [isaac sim](https://developer.nvidia.com/isaac/sim)，gazebo ,[airsim](https://github.com/microsoft/AirSim) 等等）

这个感觉可以和电控组一起讨论一下

**Comment by lunarifish** [comment]
仿真框架这个方向这个赛季有相关的内容，这赛季计划要用ros2control moveit ikfast这套东西做一个大机械臂工程，计划是先盯着做车这个目标，不管什么泛用性把这辆工程跑通，然后之后再把这一套东西改成仿真器，如果要加这部分的话可以先不急，等工程这边有一点成型之后再围绕它考虑有什么工作要做

然后还可以参考隔壁的[rm_control](https://github.com/rm-controls/rm_control)

**Comment by lunarifish** [comment]
说到仿真器就还得说强化学习，之后如果有比轮腿更复杂构型的车就一定会涉及到这方面

https://github.com/isaac-sim/IsaacLab
可以用这个东西做并行仿真，训练速度比较快，但是好像因为刚做出来没啥生态，和ros这一套东西对接要自己做？

**Comment by Gy920** [comment]
> 仿真框架这个方向这个赛季有相关的内容，这赛季计划要用ros2control moveit ikfast这套东西做一个大机械臂工程，计划是先盯着做车这个目标，不管什么泛用性把这辆工程跑通，然后之后再把这一套东西改成仿真器，如果要加这部分的话可以先不急，等工程这边有一点成型之后再围绕它考虑有什么工作要做
> 
> 然后还可以参考隔壁的[rm_control](https://github.com/rm-controls/rm_control)

目前，我们的仿真任务不太一样，我们要做的是像下面这样的，这是以前的一个demo。我们的任务需求是出自瞄系统和导航系统需要的一个输入数据（图像,imu,点云,gt等）,没有涉及到控制层。

https://github.com/user-attachments/assets/a223dbfb-bcad-44c3-90e0-b7333d784334

**Comment by Gy920** [comment]
> > 仿真框架这个方向这个赛季有相关的内容，这赛季计划要用ros2control moveit ikfast这套东西做一个大机械臂工程，计划是先盯着做车这个目标，不管什么泛用性把这辆工程跑通，然后之后再把这一套东西改成仿真器，如果要加这部分的话可以先不急，等工程这边有一点成型之后再围绕它考虑有什么工作要做
> > 然后还可以参考隔壁的[rm_control](https://github.com/rm-controls/rm_control)
> 
> 目前，我们的仿真任务不太一样，我们要做的是像下面这样的，这是以前的一个demo。我们的任务需求是出自瞄系统和导航系统需要的一个输入数据（图像,imu,点云,gt等）,没有涉及到控制层。
> 
>  sim.mp4

但能大一统还是好的，可以视控一体那边做着看看

**Comment by xiaotudou33** [comment]
换大臂挺好的，ikfast难度在于配置，仿真的话可以把ikfast给出来的解析解直接带进算法里看大臂末端机构的姿态和目标姿态的差距有多少，这样用rviz和gazebo就够了

**Comment by lunarifish** [comment]
> > 仿真框架这个方向这个赛季有相关的内容，这赛季计划要用ros2control moveit ikfast这套东西做一个大机械臂工程，计划是先盯着做车这个目标，不管什么泛用性把这辆工程跑通，然后之后再把这一套东西改成仿真器，如果要加这部分的话可以先不急，等工程这边有一点成型之后再围绕它考虑有什么工作要做
> 
> > 
> 
> > 然后还可以参考隔壁的[rm_control](https://github.com/rm-controls/rm_control)
> 
> 
> 
> 目前，我们的仿真任务不太一样，我们要做的是像下面这样的，这是以前的一个demo。我们的任务需求是出自瞄系统和导航系统需要的一个输入数据（图像,imu,点云,gt等）,没有涉及到控制层。
> 
> 
> 
> https://github.com/user-attachments/assets/a223dbfb-bcad-44c3-90e0-b7333d784334
> 
> 
> 
> 

这样的话是不是可以试试用webot？

**Comment by Gy920** [comment]
> > > 仿真框架这个方向这个赛季有相关的内容，这赛季计划要用ros2control moveit ikfast这套东西做一个大机械臂工程，计划是先盯着做车这个目标，不管什么泛用性把这辆工程跑通，然后之后再把这一套东西改成仿真器，如果要加这部分的话可以先不急，等工程这边有一点成型之后再围绕它考虑有什么工作要做
> > 
> > 
> > > 
> > 
> > 
> > > 然后还可以参考隔壁的[rm_control](https://github.com/rm-controls/rm_control)
> > 
> > 
> > 目前，我们的仿真任务不太一样，我们要做的是像下面这样的，这是以前的一个demo。我们的任务需求是出自瞄系统和导航系统需要的一个输入数据（图像,imu,点云,gt等）,没有涉及到控制层。
> > 
> >   
> >     
> >     
> > 
> >     sim.mp4
> 
> 这样的话是不是可以试试用webots？

目前用的是unity

**Comment by Gy920** [comment]
但我想讨论的是，robotic方向（机械臂）学什么

**Comment by Gy920** [comment]
> > 机械臂方向我觉得可以加（比如命名为robotic方向)，但仿真器不应该是一个大的方向，我们应该把他归结到robotic方向中的一个模块中，理由是:
> > 
> > * 我们不是做图形学上的引擎开发，其实我们所谓做的仿真器，其实是拿别人的引擎，然后放自己的场景和机器人进去，所以这个不应该是一个大方向，只是我们做机器人中的一个模块（这类仿真器比如像 [isaac sim](https://developer.nvidia.com/isaac/sim)，gazebo ,[airsim](https://github.com/microsoft/AirSim) 等等）
> 
> 一起讨论一下@xiaotudou33 @lunarifish

你们写一下，提个pr？
